In [1]:
# Importando as bibliotecas
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

import matplotlib.pyplot as plt
import seaborn as sns
from features.feature_extractor_v2 import extract_features
import pandas as pd
import joblib

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

In [2]:
from features.feature_extractor_v2 import extract_features

print(
    extract_features(
        "https://google.login-security.xyz"
    ).keys()
)

dict_keys(['NumDots', 'SubdomainLevel', 'PathLevel', 'UrlLength', 'NumDash', 'NumDashInHostname', 'AtSymbol', 'TildeSymbol', 'NumUnderscore', 'NumPercent', 'NumQueryComponents', 'NumAmpersand', 'NumHash', 'NumNumericChars', 'PctNumericChars', 'NoHttps', 'IpAddress', 'DomainInSubdomains', 'DomainInPaths', 'HostnameLength', 'PathLength', 'QueryLength', 'HttpsInHostname', 'HostnameHasDigit', 'HostnameDigitCount', 'NumSensitiveWords', 'DoubleSlashInPath', 'Has_login', 'Has_verify', 'Has_secure', 'Has_account', 'Has_update', 'Has_confirm', 'Has_signin', 'Has_bank', 'Has_payment', 'Has_wallet', 'Has_password', 'Has_security', 'Has_support', 'SuspiciousTLD', 'ManySubdomains', 'KnownBrandInURL', 'BrandInSubdomain', 'BrandInPath', 'BrandMismatch', 'SpecialCharRatio', 'LongURL', 'VeryLongURL', 'UrlEntropy', 'FreeHosting', 'RandomLookingHostname'])

In [3]:
import features.feature_extractor_v2 as fe

print(fe.__file__)

c:\Users\u513127\Downloads\phishing-project-kaggle-main\phishing-project-kaggle-main\ml\features\feature_extractor_v2.py

In [4]:
df_balanced = pd.read_csv(
    "../datasets/raw/balanced_urls.csv"
)

In [5]:
df_balanced.head()

                         url   label  result
0     https://www.google.com  benign       0
1    https://www.youtube.com  benign       0
2   https://www.facebook.com  benign       0
3      https://www.baidu.com  benign       0
4  https://www.wikipedia.org  benign       0

In [6]:
df_balanced["result"].value_counts()

result
0    316254
1    316254
Name: count, dtype: int64

In [7]:
features = df_balanced["url"].apply(
    lambda url: pd.Series(
        extract_features(url)
    )
)

In [8]:
df_features = pd.concat(
    [
        df_balanced,
        features
    ],
    axis=1
)

In [9]:
df_features.to_csv(
    "../datasets/processed/df_balanced_v2.csv",
    index=False
)

In [10]:
print(df_features.shape)
df_features.head()

(632508, 55)

,url,label,result,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,...,KnownBrandInURL,BrandInSubdomain,BrandInPath,BrandMismatch,SpecialCharRatio,LongURL,VeryLongURL,UrlEntropy,FreeHosting,RandomLookingHostname
0,https://www.google.com,benign,0,2.0,1.0,0.0,22.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.663533,0.0,0.0
1,https://www.youtube.com,benign,0,2.0,1.0,0.0,23.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.762267,0.0,0.0
2,https://www.facebook.com,benign,0,2.0,1.0,0.0,24.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.855389,0.0,0.0
3,https://www.baidu.com,benign,0,2.0,1.0,0.0,21.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.880180,0.0,0.0
4,https://www.wikipedia.org,benign,0,2.0,1.0,0.0,25.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.813661,0.0,0.0

In [11]:
from sklearn.model_selection import train_test_split

df_train, df_holdout = train_test_split(
    df_features,
    test_size=0.20,
    stratify=df_features["result"],
    random_state=42
)

In [12]:
print(df_train.shape)
print(df_holdout.shape)

(506006, 55)
(126502, 55)

In [13]:
X_train = df_train.drop(
    columns=[
        "url",
        "label",
        "result"
    ],
    errors="ignore"
)

# remover feature enviesada
X_train = X_train.drop(
    columns=["NoHttps"],
    errors="ignore"
)

y_train = df_train["result"]

In [14]:
X_test = df_holdout.drop(
    columns=[
        "url",
        "label",
        "result"
    ],
    errors="ignore"
)

# remover feature enviesada
X_test = X_test.drop(
    columns=["NoHttps"],
    errors="ignore"
)

y_test = df_holdout["result"]

In [15]:
print(X_train.shape)
print(X_test.shape)

print(y_train.shape)
print(y_test.shape)

(506006, 51)
(126502, 51)
(506006,)
(126502,)

In [16]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
Index: 506006 entries, 318973 to 498253
Data columns (total 51 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   NumDots                506006 non-null  float64
 1   SubdomainLevel         506006 non-null  float64
 2   PathLevel              506006 non-null  float64
 3   UrlLength              506006 non-null  float64
 4   NumDash                506006 non-null  float64
 5   NumDashInHostname      506006 non-null  float64
 6   AtSymbol               506006 non-null  float64
 7   TildeSymbol            506006 non-null  float64
 8   NumUnderscore          506006 non-null  float64
 9   NumPercent             506006 non-null  float64
 10  NumQueryComponents     506006 non-null  float64
 11  NumAmpersand           506006 non-null  float64
 12  NumHash                506006 non-null  float64
 13  NumNumericChars        506006 non-null  float64
 14  PctNumericChars        506006 non-null  float64
 15  IpAddress              506006 non-null  float64
 16  DomainInSubdomains     506006 non-null  float64
 17  DomainInPaths          506006 non-null  float64
 18  HostnameLength         506006 non-null  float64
 19  PathLength             506006 non-null  float64
 20  QueryLength            506006 non-null  float64
 21  HttpsInHostname        506006 non-null  float64
 22  HostnameHasDigit       506006 non-null  float64
 23  HostnameDigitCount     506006 non-null  float64
 24  NumSensitiveWords      506006 non-null  float64
 25  DoubleSlashInPath      506006 non-null  float64
 26  Has_login              506006 non-null  float64
 27  Has_verify             506006 non-null  float64
 28  Has_secure             506006 non-null  float64
 29  Has_account            506006 non-null  float64
 30  Has_update             506006 non-null  float64
 31  Has_confirm            506006 non-null  float64
 32  Has_signin             506006 non-null  float64
 33  Has_bank               506006 non-null  float64
 34  Has_payment            506006 non-null  float64
 35  Has_wallet             506006 non-null  float64
 36  Has_password           506006 non-null  float64
 37  Has_security           506006 non-null  float64
 38  Has_support            506006 non-null  float64
 39  SuspiciousTLD          506006 non-null  float64
 40  ManySubdomains         506006 non-null  float64
 41  KnownBrandInURL        506006 non-null  float64
 42  BrandInSubdomain       506006 non-null  float64
 43  BrandInPath            506006 non-null  float64
 44  BrandMismatch          506006 non-null  float64
 45  SpecialCharRatio       506006 non-null  float64
 46  LongURL                506006 non-null  float64
 47  VeryLongURL            506006 non-null  float64
 48  UrlEntropy             506006 non-null  float64
 49  FreeHosting            506006 non-null  float64
 50  RandomLookingHostname  506006 non-null  float64
dtypes: float64(51)
memory usage: 200.7 MB

In [17]:
rf = RandomForestClassifier(
    n_estimators=50,
    random_state=42,
    n_jobs=-1
)

In [18]:
rf.fit(
    X_train,
    y_train
)

RandomForestClassifier(n_estimators=50, n_jobs=-1, random_state=42)

In [19]:
rf_pred = rf.predict(X_test)

In [20]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

print(
    "Accuracy:",
    accuracy_score(y_test, rf_pred)
)

print(
    "Precision:",
    precision_score(y_test, rf_pred)
)

print(
    "Recall:",
    recall_score(y_test, rf_pred)
)

print(
    "F1:",
    f1_score(y_test, rf_pred)
)

Accuracy: 0.9523248644290209
Precision: 0.9681568268097919
Recall: 0.935416040853109
F1: 0.9515048688114632

In [21]:
print(
    classification_report(
        y_test,
        rf_pred
    )
)

              precision    recall  f1-score   support

           0       0.94      0.97      0.95     63251
           1       0.97      0.94      0.95     63251

    accuracy                           0.95    126502
   macro avg       0.95      0.95      0.95    126502
weighted avg       0.95      0.95      0.95    126502

In [22]:
confusion_matrix(
    y_test,
    rf_pred
)

array([[61305,  1946],
       [ 4085, 59166]])

In [23]:
joblib.dump(
    rf,
    "../models/scenario_3c1/rf_scenario_3c1.pkl"
)

['../models/scenario_3c1/rf_scenario_3c1.pkl']

In [24]:
joblib.dump(
    list(X_train.columns),
    "../artifacts/scenario_3c1/features_scenario_3c1.pkl"
)

['../artifacts/scenario_3c1/features_scenario_3c1.pkl']

In [25]:
feature_columns = list(X_train.columns)

joblib.dump(
    feature_columns,
    "../artifacts/scenario_3c1/feature_columns.pkl"
)

['../artifacts/scenario_3c1/feature_columns.pkl']

In [26]:
importance = pd.DataFrame({
    "feature": X_train.columns,
    "importance": rf.feature_importances_
})

importance.sort_values(
    "importance",
    ascending=False
).head(20)

               feature  importance
1       SubdomainLevel    0.199358
18      HostnameLength    0.092046
48          UrlEntropy    0.066435
0              NumDots    0.059532
19          PathLength    0.056564
3            UrlLength    0.051985
16  DomainInSubdomains    0.042178
14     PctNumericChars    0.038695
45    SpecialCharRatio    0.038044
43         BrandInPath    0.034827
20         QueryLength    0.028738
23  HostnameDigitCount    0.027841
13     NumNumericChars    0.027812
2            PathLevel    0.025393
41     KnownBrandInURL    0.025338
10  NumQueryComponents    0.020925
44       BrandMismatch    0.020899
17       DomainInPaths    0.017991
24   NumSensitiveWords    0.017729
4              NumDash    0.014343

In [27]:
df_features["complexity"] = (
    df_features["SubdomainLevel"]
    + df_features["PathLevel"]
)

df_features.sort_values(
    "complexity"
)[
    ["url", "result"]
].head(20)

                                                      url  result
434267                                     pinuppopup.com       1
434268                                     shaparaknet.ir       1
434298                                          sgn80.com       1
434316                                          semoon.mn       1
434328                                384242.799866074.cn       1
434329                                 amsonsmanpower.com       1
434331                                      mining24.info       1
434303                             yangzirivercorp.com.au       1
434214                        andromedatechnologies.co.in       1
434215                                 sign-ln-lcloud.com       1
434233                                   cy41058.tmweb.ru       1
434242                                      dubaiscout.ae       1
434255                              acikdnz-denizbank.com       1
434259                         isonsyi.inboxread28.review       1
434260                                laposteitaliane.com       1
434263                                     jaymay-owa.com       1
434453                                    activekeys.info       1
434456                               georgiastanway.co.uk       1
434170                                          maoled.ga       1
434177  pavypal.com-resolutioncenter.privacypolicy.sup...       1

In [28]:
train_pred = rf.predict(X_train)

print(
    classification_report(
        y_train,
        train_pred
    )
)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    253003
           1       1.00      1.00      1.00    253003

    accuracy                           1.00    506006
   macro avg       1.00      1.00      1.00    506006
weighted avg       1.00      1.00      1.00    506006

In [29]:
pd.crosstab(
    df_features["label"],
    df_features["result"]
)

result          0       1
label
benign     316254       0
malicious       0  316254

In [32]:
benign = df_features[df_features["result"] == 0]

benign["url"].sample(100, random_state=42).tolist()

['https://www.academon.com/Essay-Transcontinental-Railroad/29187',
 'https://www.picasaweb.google.com/TDSSkupina',
 'https://www.picktorrent.com/download/dc/3766609/bruning-saviours-discography/',
 'https://www.cbc.ca/news/quebecvotes2008/ridings/053/',
 'https://www.ccspringvalley.org/',
 'https://www.brooklynvegan.com/archives/2011/01/hunx_his_punx_t.html',
 'https://www.profile.ultimate-guitar.com/starleigh/blog/30351/',
 'https://www.wibw.com/sports/headlines/Kansas_Football_Set_To_Open_2011_Season_Hosting_McNeese_State_Saturday_128624373.html',
 'https://www.rhodeislandentertainmentlawyers.com/',
 'https://www.houseofnames.com/fairholm-family-crest',
 'https://www.youtube.com/watch?v=pKWMSUw4Eo8',
 'https://www.musicstack.com/records-cds/ras+kass',
 'https://www.youtube.com/watch?v=rIh6wYHHyjE',
 'https://www.ontheradio.net/kllc',
 'https://www.en.wikipedia.org/wiki/Fran%C3%A7ois_Benjamin',
 'https://www.weather.com/outlook/driving/interstate/cities?ix=80&reg=us&dir=we',
 'https://www.freebase.com/view/en/jerzy_neyman',
 'https://www.sporcle.com/games/g/olympics',
 'https://www.rentalo.com/vacation-rentals/cambridgema/',
 'https://www.goroundtown.com/macon/',
 'https://www.healthgrades.com/physician/dr-glenn-cohen-3xsdv/',
 'https://www.classmates.com/yearbooks/Arroyo-High-School/98959',
 'https://www.discuss.com.hk',
 'https://www.youthfootballscotland.co.uk/clubs/east-region-clubs/east-syfa-clubs',
 'https://www.legacy.com/guestbook/atlanta/sponsor-guestbook.aspx?n=richard-boyer&pid=145162984',
 'https://www.antiochdentalcenter.com/',
 'https://www.imdb.com/title/tt0091251/fullcredits',
 'https://www.hemingwaysguns.com/?page_id=91',
 'https://www.discogs.com/artist/Galt+MacDermot',
 'https://www.f60s.com/cache/t/172569.aspx',
 'https://www.pipl.com/directory/tags/Victor%2520Colicchio',
 'https://www.people.famouswhy.com/earl_hines/',
 'https://www.pastaprima.net/artist-reviews/land-of-talk/',
 'https://www.disneyanimation.com/aboutus/history.html',
 'https://www.internships.about.com/od/internshipsintechnology/a/Sony-Computer-Entertainment-America-Llcs-Mobile-Video-Game-Internship.htm',
 'https://www.startrekxisucks.blogspot.com/',
 'https://www.ask.com/questions-about/Political-Satire',
 'https://www.trekmovie.com/2010/06/26/exclusive-video-roberto-orci-alex-kurtzman-on-status-of-star-trek-sequel-discuss-importance-of-villain-title-ideas/',
 'https://www.panjiva.com/sitemap/buyer_detail?page=142',
 'https://www.guedy.info/uploads/T_J__Houshmandzadeh_-_Wikipedia__the_free_encyclopedia.htm',
 'https://www.spoke.com/info/p6ryedp/JasonCaudle',
 'https://www.msa.md.gov/msa/mdmanual/16dhmh/html/dhmhd.html',
 'https://www.opalhotelcollection.com/',
 'https://www.wiki.muscoop.com/doku.php/men_s_basketball/jack_nagle',
 'https://www.familytreeassistant.com/surnames/Hardy-family-tree.html',
 'https://www.fcafa.wordpress.com/2011/01/29/frantisek-perina/',
 'https://www.amazon.com/Rick-James-Ultimate-Collection/dp/B000001AMV',
 'https://www.ritawatson.com/?p=1811',
 'https://www.poimuri.fi/artistList/M',
 'https://www.youtube.com/watch?v=tF77E-4QGoQ',
 'https://www.ipetitions.com/petition/conradblack/',
 'https://www.home.comcast.net/~alloy-artifacts/western-auto-supply.html',
 'https://www.fullnamedirectory.com/page138603.html',
 'https://www.digital-topo-maps.com/missouri.shtml',
 'https://www.chicagowolves.com/releases/2681-sweatt-and-sauve-among-six-assigned-to-wolves',
 'https://www.redtube.com/9003',
 'https://www.imfdb.org/wiki/Mike_Chopud',
 'https://www.youtube.com/watch?v=KZ2cwMZJuTc',
 'https://www.myhomeinaz.com/',
 'https://www.experienceproject.com/song_meanings.php?song=Wind+It+Up&a=Gwen+Stefani&s=2953&t=s',
 'https://www.music.yahoo.com/pierre-flynn/',
 'https://www.liverpoolecho.co.uk/sport/other-sports/2011/06/13/jenson-button-defies-rain-and-rivals-to-win-canadian-grand-prix-100252-28867311/',
 'https://www.answers.com/topic/order-of-the-bath',
 'https://www.facebook.com/people/Dennis-Jan-McCoy/1390819834',
 'https://www.manta.com/mb_51_ALL_KFH/encinal_tx',
 'https://www.level5motorsports.com/',
 'https://www.rottentomatoes.com/m/pirate_radio/trailers/',
 'https://www.anconguild.com/1967Season.htm',
 'https://www.evri.com/organization/tooncan-0x9d02c',
 'https://www.mostlyaboutchocolate.com/green-blacks-new-burnt-toffee-dark-and-crisp-cereal-milk-chocolate-bars/',
 'https://www.thefreelibrary.com/The+Hockey+Company+Holdings+Inc.+Announces+Acquisition+of+Lifestyle...-a0106768219',
 'https://www.organicfoodfranchise.net/',
 'https://www.en.wikipedia.org/wiki/Cummings_Jewish_Centre_for_Seniors',
 'https://www.nalderfuneralhome.com/obituary.aspx?MemberId=34757&MName=Dorotha%20Fae%20Anderson',
 'https://www.en.wikipedia.org/wiki/Iowa_State_University',
 'https://www.bmi.com/press/entry/534675',
 'https://www.absoluteastronomy.com/topics/Supermarkets_in_the_United_Kingdom',
 'https://www.genforum.genealogy.com/lillie/',
 'https://www.ominousweather.com/UnionPacific1.html',
 'https://www.dollydearsofyesteryears.com/',
 'https://www.washingtonradiology.com/radiologists/greenberg.asp',
 'https://www.bellingram.co.uk/properties/sale?area=Argyll+%26+Bute',
 'https://www.youtube.com/watch?v=skV7B6_i7ZU',
 'https://www.scribd.com/doc/46807907/Commentary-on-Guiding-Principles-HRA-Earthjustice-Right-Respect',
 'https://www.theambassador.dk/',
 'https://globetrotter.berkeley.edu/conversations/',
 'https://www.quantumfrog.com/',
 'https://www.twitter.com/LeNouvelObs/statuses/139751054177869825',
 'https://www.magazine-covers.lucywho.com/kris-aquino-magazine-covers-t19695.html',
 'https://www.focusfeatures.com/9',
 'https://www.bellaward.com/',
 'https://www.zoominfo.com/people/DiTullio_James_1226716547.aspx',
 'https://www.encyclopedia2.thefreedictionary.com/Philip+the+Bold+of+France',
 'https://www.richardsonhighschool1962.com/',
 'https://www.faqs.org/sec-filings/091117/KANSAS-CITY-POWER-and-LIGHT-CO_8-K/ex99_1.htm',
 'https://www.comfortsuitesmonroe.com/html/hotel-rooms-monroe-louisiana.asp',
 'https://www.scc-csc.gc.ca/court-cour/ju/cfcju-jucp/index-eng.asp',
 'https://www.hotfrog.ca/Companies/Construction-Beaudin-Courville',
 'https://www.facebook.com/martin.ez.Houle',
 'https://www.mylife.com/c-716602044']