In [7]:
import sys
import os

sys.path.append(
    os.path.abspath("..")
)

from module.feature_extractor_v2 import extract_features
import pandas as pd

In [9]:
df = pd.read_csv("../data/datasetURL.csv")

In [10]:
df.head()

                                                 url  label   source
0                  http://110.37.26.193:54956/bin.sh      1  urlhaus
1           https://sentry5.obor1shwron8.ru/4ylkytvt      1  urlhaus
2               https://d6gu.ripple-cask.ru/jid43vpd      1  urlhaus
3  http://130.12.180.34/596a96cc7bf9108cd896f33c4...      1  urlhaus
4                             https://bronze.systems      0   tranco

In [12]:
# 5. Gerar features
features_df = pd.DataFrame(
    [extract_features(url) for url in df["url"]]
)

In [13]:
features_df.head()

,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,...,Has_signin,Has_bank,Has_payment,Has_wallet,Has_password,Has_security,Has_support,SuspiciousTLD,ManySubdomains,KnownBrandInURL
0,4,2,1,33,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,2,1,1,40,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,2,1,1,36,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,2,2,91,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,1,0,0,22,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
features_df.shape

(48812, 43)

In [15]:
features_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48812 entries, 0 to 48811
Data columns (total 43 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   NumDots             48812 non-null  int64
 1   SubdomainLevel      48812 non-null  int64
 2   PathLevel           48812 non-null  int64
 3   UrlLength           48812 non-null  int64
 4   NumDash             48812 non-null  int64
 5   NumDashInHostname   48812 non-null  int64
 6   AtSymbol            48812 non-null  int64
 7   TildeSymbol         48812 non-null  int64
 8   NumUnderscore       48812 non-null  int64
 9   NumPercent          48812 non-null  int64
 10  NumQueryComponents  48812 non-null  int64
 11  NumAmpersand        48812 non-null  int64
 12  NumHash             48812 non-null  int64
 13  NumNumericChars     48812 non-null  int64
 14  PctNumericChars     48812 non-null  float64
 15  NoHttps             48812 non-null  int64
 16  IpAddress           48812 non-null  int64
 17  DomainInSubdomains  48812 non-null  int64
 18  DomainInPaths       48812 non-null  int64
 19  HostnameLength      48812 non-null  int64
 20  PathLength          48812 non-null  int64
 21  QueryLength         48812 non-null  int64
 22  HttpsInHostname     48812 non-null  int64
 23  HostnameHasDigit    48812 non-null  int64
 24  HostnameDigitCount  48812 non-null  int64
 25  NumSensitiveWords   48812 non-null  int64
 26  DoubleSlashInPath   48812 non-null  int64
 27  Has_login           48812 non-null  int64
 28  Has_verify          48812 non-null  int64
 29  Has_secure          48812 non-null  int64
 30  Has_account         48812 non-null  int64
 31  Has_update          48812 non-null  int64
 32  Has_confirm         48812 non-null  int64
 33  Has_signin          48812 non-null  int64
 34  Has_bank            48812 non-null  int64
 35  Has_payment         48812 non-null  int64
 36  Has_wallet          48812 non-null  int64
 37  Has_password        48812 non-null  int64
 38  Has_security        48812 non-null  int64
 39  Has_support         48812 non-null  int64
 40  SuspiciousTLD       48812 non-null  int64
 41  ManySubdomains      48812 non-null  int64
 42  KnownBrandInURL     48812 non-null  int64
dtypes: float64(1), int64(42)
memory usage: 16.0 MB

In [16]:
features_df.isnull().sum()

NumDots               0
SubdomainLevel        0
PathLevel             0
UrlLength             0
NumDash               0
NumDashInHostname     0
AtSymbol              0
TildeSymbol           0
NumUnderscore         0
NumPercent            0
NumQueryComponents    0
NumAmpersand          0
NumHash               0
NumNumericChars       0
PctNumericChars       0
NoHttps               0
IpAddress             0
DomainInSubdomains    0
DomainInPaths         0
HostnameLength        0
PathLength            0
QueryLength           0
HttpsInHostname       0
HostnameHasDigit      0
HostnameDigitCount    0
NumSensitiveWords     0
DoubleSlashInPath     0
Has_login             0
Has_verify            0
Has_secure            0
Has_account           0
Has_update            0
Has_confirm           0
Has_signin            0
Has_bank              0
Has_payment           0
Has_wallet            0
Has_password          0
Has_security          0
Has_support           0
SuspiciousTLD         0
ManySubdomains        0
KnownBrandInURL       0
dtype: int64

In [17]:
df_features = pd.concat(
    [features_df, df["label"]],
    axis=1
)

In [18]:
df_features.head()

,NumDots,SubdomainLevel,PathLevel,UrlLength,NumDash,NumDashInHostname,AtSymbol,TildeSymbol,NumUnderscore,NumPercent,...,Has_bank,Has_payment,Has_wallet,Has_password,Has_security,Has_support,SuspiciousTLD,ManySubdomains,KnownBrandInURL,label
0,4,2,1,33,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
1,2,1,1,40,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,2,1,1,36,1,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,4,2,2,91,0,0,0,0,0,0,...,0,0,0,0,0,0,0,1,0,1
4,1,0,0,22,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [19]:
df_features.to_csv(
    "../data/dataset_features.csv",
    index=False
)

In [20]:
feature_stats = (
    df_features
    .groupby("label")
    .mean()
    .T
)

feature_stats

label                       0          1
NumDots              1.074859   3.177661
SubdomainLevel       0.074859   1.680202
PathLevel            0.000000   1.298902
UrlLength           20.025035  36.128247
NumDash              0.080677   0.136524
NumDashInHostname    0.080677   0.049660
AtSymbol             0.000000   0.000041
TildeSymbol          0.000000   0.000000
NumUnderscore        0.000082   0.050438
NumPercent           0.000000   0.038392
NumQueryComponents   0.000000   0.044825
NumAmpersand         0.000000   0.028313
NumHash              0.000000   0.000082
NumNumericChars      0.142383  11.544333
PctNumericChars      0.007247   0.342273
NoHttps              0.000000   0.770138
IpAddress            0.000000   0.710153
DomainInSubdomains   0.001680   0.027370
DomainInPaths        0.000000   0.004835
HostnameLength      12.025035  14.998279
PathLength           0.000000  10.458617
QueryLength          0.000000   0.931697
HttpsInHostname      0.000000   0.000656
HostnameHasDigit     0.074818   0.893715
HostnameDigitCount   0.142383   7.759444
NumSensitiveWords    0.007457   0.004712
DoubleSlashInPath    0.000000   0.000942
Has_login            0.000246   0.000901
Has_verify           0.000082   0.000164
Has_secure           0.000778   0.000164
Has_account          0.000123   0.000246
Has_update           0.000287   0.001475
Has_confirm          0.000082   0.000000
Has_signin           0.000000   0.000000
Has_bank             0.003647   0.001147
Has_payment          0.000205   0.000123
Has_wallet           0.000246   0.000123
Has_password         0.000123   0.000000
Has_security         0.001352   0.000287
Has_support          0.000287   0.000082
SuspiciousTLD        0.003647   0.007252
ManySubdomains       0.000369   0.720601
KnownBrandInURL      0.008359   0.004589

In [21]:
corr = (
    df_features
    .drop(columns=["label"])
    .corr()
)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12,8))

sns.heatmap(
    corr,
    cmap="coolwarm",
    center=0
)

plt.show()

In [23]:
df_features["IpAddress"].value_counts()

IpAddress
0    31480
1    17332
Name: count, dtype: int64

In [24]:
df[df_features["IpAddress"] == 1]["url"].head(20)

0                     http://110.37.26.193:54956/bin.sh
3     http://130.12.180.34/596a96cc7bf9108cd896f33c4...
8                         http://222.137.23.188:37413/i
9                       http://60.18.96.56:56269/bin.sh
10                          http://115.57.11.32:35490/i
12                         http://110.37.18.205:43889/i
13                  http://175.167.164.207:38449/bin.sh
21                        http://112.231.62.159:49560/i
26                                https://96.125.189.7/
31      http://149.104.79.203/Pandoras_Box/pandora.mpsl
32                       http://182.121.154.114:47877/i
33                  http://182.143.113.175:81/Photo.scr
35                        http://222.141.101.29:60225/i
37             http://91.92.243.68/Fantazy/Fantazy.mpsl
38                             http://1.53.249.172/sshd
46                     http://200.59.83.32:48758/bin.sh
47                    http://39.187.66.105:43484/bin.sh
54                          http://39.74.91.111:36175/i
57     http://178.16.55.189/files/380743829/BjhIEkS.exe
58                          http://5.27.166.115:47371/i
Name: url, dtype: object

In [ ]:
corr_label = (
    df_features
    .corr(numeric_only=True)["label"]
    .sort_values(ascending=False)
)

corr_label