In [28]:
import pandas as pd

df_tranco = pd.read_csv(
    "../buildingdb/tranco.csv",
    header=None,
    names=["rank", "domain"]
)

df_tranco["url"] = "https://" + df_tranco["domain"]
df_tranco["label"] = 0
df_tranco["source"] = "tranco"

df_tranco = df_tranco[
    ["url", "label", "source"]
]

In [29]:
df_tranco.head()

                        url  label  source
0        https://google.com      0  tranco
1  https://gtld-servers.net      0  tranco
2    https://cloudflare.com      0  tranco
3       https://gstatic.com      0  tranco
4      https://facebook.com      0  tranco

In [30]:
with open(
    "../buildingdb/phishingGit.txt",
    "r",
    encoding="utf-8",
    errors="ignore"
) as f:

    urls = [
        linha.strip()
        for linha in f
        if linha.strip()
    ]

df_phishingdb = pd.DataFrame({
    "url": urls
})

df_phishingdb["label"] = 1
df_phishingdb["source"] = "phishingdb"

In [31]:
df_phishingdb.shape

(57967, 3)

In [32]:
print(len(df_phishingdb))
print(df_phishingdb["url"].nunique())

57967
57967

In [33]:
df_phishingdb.sample(20, random_state=42)

                                                     url  label      source
43192                http://alrbnb-verify.com-id1081.com      1  phishingdb
31927  http://accesso-intesa-sanpaolo-sicurezza-conto...      1  phishingdb
12522                  http://34a976a3.if9odn.shop/amagc      1  phishingdb
57051                    http://usps.com-trackepk.top/us      1  phishingdb
39088  http://ahteghfdkhhrlcxh-dot-millinium.ey.r.app...      1  phishingdb
33049  http://account-support.dynamic-dns.net/../myac...      1  phishingdb
1221           http://104.168.137.248/confrim99834.co.vu      1  phishingdb
35845                            http://admin.gom-yk.top      1  phishingdb
38042  http://ageless-aleph-278010.dt.r.appspot.com/h...      1  phishingdb
45967  http://amcgardiennage.com/p2w9zizpptfqmmg5aji5...      1  phishingdb
24279                  http://772cc828.selang77.cn/amagc      1  phishingdb
53334      https://janatarcrime.com/M3o4dDVqNVc0QjhIMzQ=      1  phishingdb
45567  http://amazon.usexpress.com.vn/stores/page/b4a...      1  phishingdb
29933                   http://aarlosmado.temp.swtest.ru      1  phishingdb
55768                   https://usps.com-trackxla.top/us      1  phishingdb
8510   http://204.152.210.132/index.php/false/files/f...      1  phishingdb
14902                                http://3or5.es/help      1  phishingdb
2826   http://1636365.com/assets/40popperjs.36402333....      1  phishingdb
11088  http://2itaucard.com/home.php?l/dyjmysg6rlw6br...      1  phishingdb
2515   http://162-212-152-19.cprapid.com/La-Suisse-Po...      1  phishingdb

In [34]:
N = 57967
df_legit = df_tranco.sample(
    n=N,
    random_state=42
)

df_phish = df_phishingdb.sample(
    n=N,
    random_state=42
)

In [35]:
df_final = pd.concat(
    [df_legit, df_phish],
    ignore_index=True
)

df_final = df_final.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [36]:
df_final.head()

                                                 url  label      source
0     https://start-ledggee-cdn.teachable.com/p/home      1  phishingdb
1  http://43.153.192.86/v3/signin/identifier?dsh=...      1  phishingdb
2          http://63179679.satgrjtxcvdv.org.cn/amagc      1  phishingdb
3  http://amber-kh.com/dollarman/ujhost/Account%2...      1  phishingdb
4  http://207.154.253.64/banks/CIBC/4fdb6096796be...      1  phishingdb

In [37]:
df_final["label"].value_counts()

label
1    57967
0    57967
Name: count, dtype: int64