In [ ]:
import pandas as pd

df = pd.read_csv("../datasets/raw/malicious_phish.csv")

df.head()

                                                 url        type
0                                   br-icloud.com.br    phishing
1                mp3raid.com/music/krizz_kaliko.html      benign
2                    bopsecrets.org/rexroth/cr/1.htm      benign
3  http://www.garage-pirenne.be/index.php?option=...  defacement
4  http://adventure-nicaragua.net/index.php?optio...  defacement

In [39]:
df["type"].value_counts()

type
benign        428103
defacement     96457
phishing       94111
malware        32520
Name: count, dtype: int64

In [40]:
df_benign = (
    df[df["type"] == "benign"]
    .copy()
)

df_benign["label"] = 0
df_benign["source"] = "kaggle_benign"

In [41]:
df_benign.sample(
    20,
    random_state=42
)

,url,type,label,source
514768,montreal.louer.com/ahuntsic-rentals/houses-rent/,benign,0,kaggle_benign
222536,comunidade.sol.pt/blogs/hytigin/default.aspx,benign,0,kaggle_benign
276748,youtube.com/watch?v=PUDOlyCpHwo,benign,0,kaggle_benign
50193,uiowa.edu/~acadtech/phonetics/,benign,0,kaggle_benign
339822,flixster.com/actor/steve-mcqueen,benign,0,kaggle_benign
174885,http://stackoverflow.com/questions/5069876/reg...,benign,0,kaggle_benign
187420,en.goldenmap.com/City_of_Playford,benign,0,kaggle_benign
434789,content.usatoday.com/community/tags/topic.aspx...,benign,0,kaggle_benign
153097,music.concordia.ca/,benign,0,kaggle_benign
50095,en.wikipedia.org/wiki/Aveos_Fleet_Performance,benign,0,kaggle_benign
175357,informatica.techtiks.com/beginners.html,benign,0,kaggle_benign
158942,leftoutside.wordpress.com/,benign,0,kaggle_benign
227728,http://icicibank.com/privilege-banking/persona...,benign,0,kaggle_benign
303058,facebook.com/people/Alvin-Sanders/1378200379,benign,0,kaggle_benign
595589,'9d345009-a-62cb3a1a-s-sites.googlegroups.com/...,benign,0,kaggle_benign
411452,fanpix.net/gallery/cam-clarke-pictures.htm,benign,0,kaggle_benign
43298,facebook.com/people/Bobby-Halford/1074705824,benign,0,kaggle_benign
247321,800padutch.com/mem-out.shtml,benign,0,kaggle_benign
518020,chinatownology.com/chinatown_montreal.html,benign,0,kaggle_benign
236737,worldwidescience.org/topicpages/a/acute+myocar...,benign,0,kaggle_benign

In [ ]:
with open(
    "../datasets/raw/phishingGit.txt",
    "r",
    encoding="utf-8",
    errors="ignore"
) as f:

    urls = [
        linha.strip()
        for linha in f
        if linha.strip()
    ]

df_phishingdb = pd.DataFrame({
    "url": urls
})

df_phishingdb["label"] = 1
df_phishingdb["source"] = "phishingdb"

In [31]:
df_phishingdb.shape

(57967, 3)

In [32]:
print(len(df_phishingdb))
print(df_phishingdb["url"].nunique())

57967
57967

In [33]:
df_phishingdb.sample(20, random_state=42)

                                                     url  label      source
43192                http://alrbnb-verify.com-id1081.com      1  phishingdb
31927  http://accesso-intesa-sanpaolo-sicurezza-conto...      1  phishingdb
12522                  http://34a976a3.if9odn.shop/amagc      1  phishingdb
57051                    http://usps.com-trackepk.top/us      1  phishingdb
39088  http://ahteghfdkhhrlcxh-dot-millinium.ey.r.app...      1  phishingdb
33049  http://account-support.dynamic-dns.net/../myac...      1  phishingdb
1221           http://104.168.137.248/confrim99834.co.vu      1  phishingdb
35845                            http://admin.gom-yk.top      1  phishingdb
38042  http://ageless-aleph-278010.dt.r.appspot.com/h...      1  phishingdb
45967  http://amcgardiennage.com/p2w9zizpptfqmmg5aji5...      1  phishingdb
24279                  http://772cc828.selang77.cn/amagc      1  phishingdb
53334      https://janatarcrime.com/M3o4dDVqNVc0QjhIMzQ=      1  phishingdb
45567  http://amazon.usexpress.com.vn/stores/page/b4a...      1  phishingdb
29933                   http://aarlosmado.temp.swtest.ru      1  phishingdb
55768                   https://usps.com-trackxla.top/us      1  phishingdb
8510   http://204.152.210.132/index.php/false/files/f...      1  phishingdb
14902                                http://3or5.es/help      1  phishingdb
2826   http://1636365.com/assets/40popperjs.36402333....      1  phishingdb
11088  http://2itaucard.com/home.php?l/dyjmysg6rlw6br...      1  phishingdb
2515   http://162-212-152-19.cprapid.com/La-Suisse-Po...      1  phishingdb

In [43]:
N = 57967

df_legit = (
    df_benign
    .sample(n=N, random_state=42)
)

df_phish = (
    df_phishingdb
    .sample(n=N, random_state=42)
)

In [ ]:
df_built = pd.concat(
    [df_legit, df_phish],
    ignore_index=True
)

df_built = df_built.sample(
    frac=1,
    random_state=42
).reset_index(drop=True)

In [ ]:
df_built.head()

                                                 url type  label      source
0     https://start-ledggee-cdn.teachable.com/p/home  NaN      1  phishingdb
1  http://43.153.192.86/v3/signin/identifier?dsh=...  NaN      1  phishingdb
2          http://63179679.satgrjtxcvdv.org.cn/amagc  NaN      1  phishingdb
3  http://amber-kh.com/dollarman/ujhost/Account%2...  NaN      1  phishingdb
4  http://207.154.253.64/banks/CIBC/4fdb6096796be...  NaN      1  phishingdb

In [ ]:
df_built["label"].value_counts()

label
1    57967
0    57967
Name: count, dtype: int64

In [ ]:
df_built.drop(columns="type", inplace=True)

df_built.head()

                                                 url  label      source
0     https://start-ledggee-cdn.teachable.com/p/home      1  phishingdb
1  http://43.153.192.86/v3/signin/identifier?dsh=...      1  phishingdb
2          http://63179679.satgrjtxcvdv.org.cn/amagc      1  phishingdb
3  http://amber-kh.com/dollarman/ujhost/Account%2...      1  phishingdb
4  http://207.154.253.64/banks/CIBC/4fdb6096796be...      1  phishingdb

In [ ]:
df_built.to_csv("../datasets/interim/df_built.csv", index=False)